name: CD

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy On Local Machine
    runs-on:
      - self-hosted
      - windows
      - local

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Stop previous project containers
        run: docker compose -p nhom12 down
        shell: powershell
        working-directory: ./doan

      - name: Stop current project containers
        run: docker compose down
        shell: powershell
        working-directory: ./doan

      - name: Build and start services
        run: docker compose up -d --build
        shell: powershell
        working-directory: ./doan

      - name: Show running containers
        run: docker ps
        shell: powershell
